const continentMapping: Record<string, string> = {
  // North America
  'united states': 'North America',
  'united states of america': 'North America',
  'usa': 'North America',
  'canada': 'North America',
  'mexico': 'North America',
  'guatemala': 'North America',
  'belize': 'North America',
  'honduras': 'North America',
  'el salvador': 'North America',
  'nicaragua': 'North America',
  'costa rica': 'North America',
  'panama': 'North America',
  'cuba': 'North America',
  'jamaica': 'North America',
  'bahamas': 'North America',
  'haiti': 'North America',
  'dominican republic': 'North America',
  'puerto rico': 'North America',
  'greenland': 'North America',
  
  // South America
  'brazil': 'South America',
  'brasil': 'South America',
  'argentina': 'South America',
  'chile': 'South America',
  'colombia': 'South America',
  'peru': 'South America',
  'venezuela': 'South America',
  'ecuador': 'South America',
  'bolivia': 'South America',
  'paraguay': 'South America',
  'uruguay': 'South America',
  'guyana': 'South America',
  'suriname': 'South America',
  'french guiana': 'South America',

  // Europe
  'united kingdom': 'Europe',
  'uk': 'Europe',
  'gb': 'Europe',
  'great britain': 'Europe',
  'england': 'Europe',
  'scotland': 'Europe',
  'wales': 'Europe',
  'ireland': 'Europe',
  'france': 'Europe',
  'germany': 'Europe',
  'italy': 'Europe',
  'spain': 'Europe',
  'portugal': 'Europe',
  'netherlands': 'Europe',
  'belgium': 'Europe',
  'switzerland': 'Europe',
  'austria': 'Europe',
  'sweden': 'Europe',
  'norway': 'Europe',
  'denmark': 'Europe',
  'finland': 'Europe',
  'poland': 'Europe',
  'greece': 'Europe',
  'turkey': 'Europe',
  'russia': 'Europe',
  'ukraine': 'Europe',
  'czech republic': 'Europe',
  'czechia': 'Europe',
  'slovakia': 'Europe',
  'hungary': 'Europe',
  'romania': 'Europe',
  'bulgaria': 'Europe',
  'croatia': 'Europe',
  'serbia': 'Europe',
  'slovenia': 'Europe',
  'bosnia': 'Europe',
  'montenegro': 'Europe',
  'albania': 'Europe',
  'macedonia': 'Europe',
  'iceland': 'Europe',
  'estonia': 'Europe',
  'latvia': 'Europe',
  'lithuania': 'Europe',
  'luxembourg': 'Europe',
  'malta': 'Europe',
  'cyprus': 'Europe',

  // Asia
  'china': 'Asia',
  'japan': 'Asia',
  'india': 'Asia',
  'south korea': 'Asia',
  'korea': 'Asia',
  'north korea': 'Asia',
  'indonesia': 'Asia',
  'philippines': 'Asia',
  'vietnam': 'Asia',
  'thailand': 'Asia',
  'malaysia': 'Asia',
  'singapore': 'Asia',
  'taiwan': 'Asia',
  'hong kong': 'Asia',
  'macau': 'Asia',
  'pakistan': 'Asia',
  'bangladesh': 'Asia',
  'sri lanka': 'Asia',
  'nepal': 'Asia',
  'afghanistan': 'Asia',
  'iran': 'Asia',
  'iraq': 'Asia',
  'saudi arabia': 'Asia',
  'united arab emirates': 'Asia',
  'uae': 'Asia',
  'israel': 'Asia',
  'palestine': 'Asia',
  'jordan': 'Asia',
  'lebanon': 'Asia',
  'syria': 'Asia',
  'kazakhstan': 'Asia',
  'uzbekistan': 'Asia',
  'kyrgyzstan': 'Asia',
  'tajikistan': 'Asia',
  'turkmenistan': 'Asia',
  'myanmar': 'Asia',
  'burma': 'Asia',
  'cambodia': 'Asia',
  'laos': 'Asia',
  'mongolia': 'Asia',
  'maldives': 'Asia',

  // Africa
  'egypt': 'Africa',
  'south africa': 'Africa',
  'nigeria': 'Africa',
  'kenya': 'Africa',
  'morocco': 'Africa',
  'algeria': 'Africa',
  'tunisia': 'Africa',
  'libya': 'Africa',
  'ethiopia': 'Africa',
  'ghana': 'Africa',
  'uganda': 'Africa',
  'tanzania': 'Africa',
  'senegal': 'Africa',
  'madagascar': 'Africa',
  'angola': 'Africa',
  'mozambique': 'Africa',
  'zimbabwe': 'Africa',
  'zambia': 'Africa',
  'sudan': 'Africa',
  'ivory coast': 'Africa',
  'cote d\'ivoire': 'Africa',
  'cameroon': 'Africa',
  'rwanda': 'Africa',
  'somalia': 'Africa',
  'namibia': 'Africa',
  'botswana': 'Africa',

  // Oceania
  'australia': 'Oceania',
  'new zealand': 'Oceania',
  'fiji': 'Oceania',
  'papua new guinea': 'Oceania',
  'samoa': 'Oceania',
  'tonga': 'Oceania',
  'vanuatu': 'Oceania',
  'solomon islands': 'Oceania',
  'micronesia': 'Oceania',

  // Antarctica
  'antarctica': 'Antarctica'
};

export function getContinentByCountry(countryName: string): string {
  const norm = countryName.trim().toLowerCase();
  
  // Direct lookup
  if (continentMapping[norm]) {
    return continentMapping[norm];
  }
  
  // Substring matching
  for (const [key, continent] of Object.entries(continentMapping)) {
    if (norm.includes(key) || key.includes(norm)) {
      return continent;
    }
  }
  
  // Fallbacks
  return 'Europe'; // Default fallback
}
