export const defaultCategoryRules: Record<string, string> = {
  // Produce
  apple: 'Produce',
  apples: 'Produce',
  banana: 'Produce',
  bananas: 'Produce',
  orange: 'Produce',
  oranges: 'Produce',
  avocado: 'Produce',
  avocados: 'Produce',
  tomato: 'Produce',
  tomatoes: 'Produce',
  potato: 'Produce',
  potatoes: 'Produce',
  onion: 'Produce',
  onions: 'Produce',
  garlic: 'Produce',
  lettuce: 'Produce',
  spinach: 'Produce',
  kale: 'Produce',
  broccoli: 'Produce',
  carrot: 'Produce',
  carrots: 'Produce',
  lemon: 'Produce',
  lemons: 'Produce',
  lime: 'Produce',
  limes: 'Produce',
  berries: 'Produce',
  strawberry: 'Produce',
  strawberries: 'Produce',
  blueberry: 'Produce',
  blueberries: 'Produce',
  cucumber: 'Produce',
  pepper: 'Produce',
  peppers: 'Produce',
  mushroom: 'Produce',
  mushrooms: 'Produce',
  herbs: 'Produce',
  cilantro: 'Produce',
  parsley: 'Produce',
  ginger: 'Produce',

  // Dairy & Refrigerated
  milk: 'Dairy & Eggs',
  'oat milk': 'Dairy & Eggs',
  'almond milk': 'Dairy & Eggs',
  eggs: 'Dairy & Eggs',
  egg: 'Dairy & Eggs',
  butter: 'Dairy & Eggs',
  cheese: 'Dairy & Eggs',
  cheddar: 'Dairy & Eggs',
  parmesan: 'Dairy & Eggs',
  mozzarella: 'Dairy & Eggs',
  yogurt: 'Dairy & Eggs',
  cream: 'Dairy & Eggs',
  'sour cream': 'Dairy & Eggs',
  tofu: 'Dairy & Eggs',

  // Bakery
  bread: 'Bakery',
  bagel: 'Bakery',
  bagels: 'Bakery',
  croissant: 'Bakery',
  croissants: 'Bakery',
  tortillas: 'Bakery',
  pita: 'Bakery',
  buns: 'Bakery',

  // Meat & Seafood
  chicken: 'Meat & Seafood',
  beef: 'Meat & Seafood',
  steak: 'Meat & Seafood',
  ground: 'Meat & Seafood',
  pork: 'Meat & Seafood',
  bacon: 'Meat & Seafood',
  salmon: 'Meat & Seafood',
  fish: 'Meat & Seafood',
  shrimp: 'Meat & Seafood',
  turkey: 'Meat & Seafood',
  sausage: 'Meat & Seafood',

  // Pantry
  rice: 'Pantry',
  pasta: 'Pantry',
  spaghetti: 'Pantry',
  noodles: 'Pantry',
  beans: 'Pantry',
  olive: 'Pantry',
  oil: 'Pantry',
  vinegar: 'Pantry',
  salt: 'Pantry',
  sugar: 'Pantry',
  flour: 'Pantry',
  cereal: 'Pantry',
  oats: 'Pantry',
  oatmeal: 'Pantry',
  sauce: 'Pantry',
  spices: 'Pantry',
  coffee: 'Pantry',
  tea: 'Pantry',
  canned: 'Pantry',
  tuna: 'Pantry',
  soup: 'Pantry',
  peanut: 'Pantry',
  jam: 'Pantry',
  honey: 'Pantry',

  // Snacks & Beverages
  chips: 'Snacks & Drinks',
  cookies: 'Snacks & Drinks',
  chocolate: 'Snacks & Drinks',
  crackers: 'Snacks & Drinks',
  nuts: 'Snacks & Drinks',
  soda: 'Snacks & Drinks',
  juice: 'Snacks & Drinks',
  water: 'Snacks & Drinks',
  sparkling: 'Snacks & Drinks',
  wine: 'Snacks & Drinks',
  beer: 'Snacks & Drinks',

  // Frozen
  frozen: 'Frozen',
  ice: 'Frozen',
  'ice cream': 'Frozen',
  pizza: 'Frozen',
  peas: 'Frozen',
  berries_frozen: 'Frozen',

  // Household & Personal
  paper: 'Household',
  towels: 'Household',
  tissue: 'Household',
  tissues: 'Household',
  soap: 'Household',
  detergent: 'Household',
  sponge: 'Household',
  cleaner: 'Household',
  trash: 'Household',
  bags: 'Household',
  shampoo: 'Household',
  toothpaste: 'Household'
};

export function inferCategory(name: string): string {
  const lower = name.toLowerCase().trim();
  for (const [keyword, category] of Object.entries(defaultCategoryRules)) {
    if (lower.includes(keyword)) {
      return category;
    }
  }
  return 'Pantry';
}
